Feature/map
tobicorradi/rootstrap-target pull request #5
Opened 2022-05-20 17:29 UTC by tobicorradi

## Pull request type

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the new behavior?

- User can now see the map once the log in it's completed.
## Other information

- Stack: React, Typescript, React Router, React Hook Form, Axios, Yup, Tailwind css and Redux Toolkit

## Preview

<img width="269" alt="Screen Shot 2022-05-20 at 13 08 57" src="https://user-images.githubusercontent.com/72103735/169568530-1e5da57f-7d54-48d9-8c62-3be7a361e390.png">

<img width="1437" alt="Screen Shot 2022-05-20 at 13 11 56" src="https://user-images.githubusercontent.com/72103735/169569248-e2d69619-0a76-4c8f-bc45-d4ba0bfc8c7b.png">

2022-05-20 17:32 UTC, juanfopaez requested changes

2022-05-20 17:32 UTC, juanfopaez commented on src/components/common/Map/index.tsx
> +        url={`https://api.mapbox.com/styles/v1/tobicorradi/cl3el2qne000o15pkcygzhmbq/tiles/{z}/{x}/{y}?access_token=${TOKEN}`}
Save this url into a const an reuse it here :)

2022-05-20 17:32 UTC, juanfopaez commented on .env
> +VITE_MAP_ACCESS_TOKEN=pk.eyJ1IjoidG9iaWNvcnJhZGkiLCJhIjoiY2wzZWxjNHI3MDFsNDNkbDU5ejdoMmZ4MSJ9.EmRIQFziQMHrCb4tSPbQ7Q
Add extra line here please :)

2022-05-20 17:32 UTC, juanfopaez commented on src/index.css
> +}
Add new extra line here :)

2022-05-20 18:08 UTC, juanfopaez approved these changes
good job 🆒

2022-05-23 15:11 UTC, natokra approved these changes

2022-05-23 16:34 UTC, merged